name: build-golang

on:
  push:
    paths:
      - '.github/workflows/build-golang.yml'
      - '.version'
      - 'go.Dockerfile'

jobs:
  build-golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: make go
      


